### ISSUE TITLE
App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure.

### ISSUE THREAD

**Issue by ryanjbonnell** [paulhammond/webkit2png#100]
When using webkit2png on newer versions of macOS, it fails with the following message:

```
$ webkit2png http://example.com/

Fetching http://example.com/ ...

2017-01-10 11:33:53.086 Python[93743:4797042]
App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure.

Temporary exceptions can be configured via your app's Info.plist file.

... something went wrong: The resource could not be loaded because
the App Transport Security policy requires the use of a secure connection.
```

Installed via **Homebrew** 1.1.6-45-g9cce341 and tested using **webkit2png** 0.7 on **macOS** 10.12.2 "Sierra" with **Python** 2.7.10.

**Comment by ryanjbonnell** [comment]
It looks like this issue has been ongoing since October 2015 and reported in https://github.com/paulhammond/webkit2png/issues/90 and https://github.com/paulhammond/webkit2png/issues/99, but still not fixed.

**Comment by ryanjbonnell** [comment]
The pull request from @bendalton (https://github.com/paulhammond/webkit2png/pull/91) seems to fix the problem when using the `--ignore-ssl-check` option:

```
$ webkit2png --ignore-ssl-check -D ~/Desktop http://www.google.com/
```

Can we get his pull request merged into master (and the version in Homebrew updated)?

**Comment by dpollardcouk** [comment]
Alas using the --ignore-ssl-check doesnt work for me using 08-dev on Mac Sierra 10.12.5

**Comment by Germain-Italic** [comment]
up...

**Comment by politicus** [comment]
@ryanjbonnell I tried the fix and didn't work. 

Installed webkit2png today via homebrew. 

webkit2png 0.7
Mac OS X 10.12.6.

How to install it without homebrew? I got I need to download the script. But before making my file executable, how do I have to save the file in /usr/local/bin? As an .sh file? A .txt file? Thank you.

**Comment by politicus** [comment]
Installing @orenyomtov version you can find [here](https://github.com/paulhammond/webkit2png/issues/90#issuecomment-222379991) and the `--ignore-ssl-check ` option helped me not having the App Transport Security error message.

Configuration 
webkit2png 0.7
Mac OS X 10.12.6

**Comment by glamrock** [comment]
Same situation, and using `--ignore-ssl-check` didn't resolve the issue. I installed via homebrew (OSX 10.11.6)

**Comment by ryanjbonnell** [comment]
When installing the Homebrew formula for webkit2png 0.7 on macOS High Sierra 10.13.3, the `--ignore-ssl-check` option can be used to create screenshots without getting the App Transport Security error:

```
$ brew install webkit2png

$ sw_vers -productVersion && brew -v && webkit2png --v

  10.13.3
  Homebrew 1.5.5
  Homebrew/homebrew-core (git revision 8bac; last commit 2018-02-28)
  webkit2png 0.7

$ webkit2png -D ~/Desktop https://www.example.com/
```

It appears a change (?) in 10.13 now allows this to work, despite throwing errors in earlier versions of macOS.

---

**Thus, if you're using macOS "High Sierra" 10.13.x, the neglected 4+ year old, version 0.7 of webkit2png in Homebrew seems to work again _without needing to specify the `--ignore-ssl-check` option._**

**Comment by o6uoq** [comment]
+1

**Comment by rutgervalk** [comment]
The issue still persists, even with 0.7...

**Comment by ryanjbonnell** [comment]
A brief update for anyone using newer versions of Mac OS X.

I just tested webkit2png 0.7 on macOS 10.14 "Mojave" and it worked successfully without the App Transport Security errors mentioned here..

Below is the output of my Homebrew environment:

```
$ sw_vers -productVersion && brew -v && webkit2png --v
10.14
Homebrew 1.7.6
Homebrew/homebrew-core (git revision eeb0; last commit 2018-09-27)
Homebrew/homebrew-cask (git revision c9f62; last commit 2018-09-27)
webkit2png 0.7
```
---

As mentioned previously, macOS 10.11 "El Capitan" and 10.12 "Sierra" exhibit the _App Transport Security_ errors, but 10.13 "High Sierra" and 10.14 "Mojave" work out of the box and do not require specifying the `--ignore-ssl-check` option.

**Comment by metaColin** [comment]
I hate to contradict other reports, but this issue most definitely present in OS X Mojave (10.14.1).

I just did a fresh install of Mojave on my MBP, installed webkit2png via Brew. When I try to use webkit2png it returns the _App Transport Security_ error as described by others.

For now I will have to use the '--ignore-ssl-check' when using this tool.

The error:
```
$ webkit2png http://example.com/

Fetching http://example.com/ ...

2018-12-05 12:55:36.222 Python[17168:1435133] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.  

 ... something went wrong: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.
```

My version info:
```
$ sw_vers -productVersion && brew -v && webkit2png --v . 

10.14.1
Homebrew 1.8.4
Homebrew/homebrew-core (git revision 78fa; last commit 2018-12-05)
webkit2png 0.7
```

**Comment by sikosis** [comment]
Not working for me ...

```
webkit2png --ignore-ssl-check http://sikosis.com
Fetching http://sikosis.com ...
2019-03-05 09:37:49.492 Python[56746:21132618] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
 ... something went wrong: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.
```

`sw_vers -productVersion && brew -v && webkit2png --v
10.13.6
Homebrew 2.0.2
Homebrew/homebrew-core (git revision 0f646; last commit 2019-03-04)
Homebrew/homebrew-cask (git revision 19b37; last commit 2019-03-04)
webkit2png 0.7
`

**Comment by paulhammond** [comment]
Hi all! Thank you to everyone for reporting this and for the comments helping each other out. I'm sorry it took so long to get this fixed; my day job got really really busy and side projects like webkit2png got left behind.

I'll be releasing a new version soon that includes this fix.

**Comment by toniengelhardt** [comment]
When will 0.8 with the fix be released?
