### ISSUE TITLE
Add text to filename with current screenshot URL 

### ISSUE THREAD

**Issue by YuriKislitsin** [paulhammond/webkit2png#101]
How can I add some text inside screenshot filename?

For example, with google.com, I need to add #P in filename with current screenshot url, to receive #P-wwwgooglecom-full.png
How this be done?

Thank you for your work!

**Comment by p-eh** [comment]
wondering the same thing here. Did you ever find a solve for this?

**Comment by paulhammond** [comment]
Hi, you can use `--filename=foo` to give the image any needed filename. Hope this helps!
