### ISSUE TITLE
WebP images returned blank

### ISSUE THREAD

**Issue by hablema** [paulhammond/webkit2png#104]
I'm trying to take a screenshot of a website with webP images. I get blank placeholders in place of the webP images. Is there any way I could grab those pages.

Try for example this

`webkit2png https://developers.google.com/speed/webp/gallery1`

**Comment by paulhammond** [comment]
Safari and webkit [don't support webP images](https://caniuse.com/#feat=webp) and webkit2png uses the same rendering engine and so supports whatever they support.

If you need to capture screenshots of pages that use webP you could try using [Headless Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome).

Sorry I can't be more help!
