### ISSUE TITLE
Add timestamp to filename

### ISSUE THREAD

**Issue by phawsea** [paulhammond/webkit2png#105]
I need to make screenshots every 30 minutes. Therefore I need to add a timestamp (not just datestamp) to my filename.

**Comment by paulhammond** [comment]
You can specify any filename you want with the `--filename` option. You can combine that with the `date` command like this:
```
webkit2png https://www.example.com --filename="example-$(date +%Y-%m-%d-%T)"
```
and get a file called `2020-03-25-19:46:13-full.png`.

Hope this helps!
