### ISSUE TITLE
Specifying a small canvas size doesn't work

### ISSUE THREAD

**Issue by kevbo** [paulhammond/webkit2png#12]
When I set the h/w to, for example, 320x365 (for capturing the canvas of an iPhone-targeted site in portrait mode), the actual screengrab ends up being 8xx by 8xx anyway. I've worked around this locally by adding an -iphone option that overrides options.[height, width, initHeight, initWidth], but in an overtly hacky way.

**Comment by paulhammond** [comment]
Closing in favor of #109
