### ISSUE TITLE
README.md should mention OS X dependency

### ISSUE THREAD

**Issue by hartwork** [paulhammond/webkit2png#55]
If I am not mistaken, webkit2png depends on Python package Quartz, a python wrapper around OS X' CoreGraphics. If so, Linux (and Windows) users would only waste their time trying to get it to run. Please add a note. Thank you!

**Comment by paulhammond** [comment]
This is fixed in 4550a8893b8bbdd7dc02accbb5ac6c7f32a09012. Thanks again for pointing it out!
