### ISSUE TITLE
Screengrabbing local file with query string doesn't work

### ISSUE THREAD

**Issue by dulnan** [paulhammond/webkit2png#59]
I tried to run the script to take a screenshot of a local html file with a query string:

```
$ webkit2png /tmp/file.html?test=test
Fetching file://localhost/tmp/file.html%3Ftest=test ...
 ... something went wrong: The requested URL was not found on this server.
```

**Comment by NetTango** [comment]
One extra note: if you have multiple query parameters (separated by &), make sure to escape these on the command line:
webkit2png file:///tmp/file.html?test=test\&second=more+tests
