### ISSUE TITLE
Grabbing an element by CSS class when it has more than one class

### ISSUE THREAD

**Issue by reibejoy** [paulhammond/webkit2png#69]
Hello, 

I was not able to specifically grab an element when it had more than on css class applied and I wanted to select by the 2nd class. 

Code:

<table class="egmSnippetContent egmMatchInfoLineup">
...
</table>

I want to grab by ".egmMatchInfoLineup" 

Running this query:
/usr/local/bin/webkit2png '/Users/jan/Desktop/greb/single-saf.html' -F --selector=.egmSnippetContent -o saf 

throws an error. Unfortunately I don't know how to debug, so sorry for trying to get some help this way. If there is another / preferred way, please let me know. 

best, 
Jan

**Comment by paulhammond** [comment]
Hi Jan, Sorry for not replying for 6 years. It's hard to tell what's wrong based on the information you've given and you probably moved onto other things a long time ago, so I'm going to close this bug out. If you still want to get this to work, feel free to reopen this bug with some more details like an example of the HTML you're using and I'll look into it. Thanks!
