### ISSUE TITLE
HELP: How to run it in webserver?

### ISSUE THREAD

**Issue by iosoft** [paulhammond/webkit2png#77]
Hello,

I am not a Python guy so I need your kind help to make it run in my webserver.

My webserver runs with Apache PHP MySQL. Its a shared webserver.
It supports CGI and has a cgi-bin directory.
I can run 'Hello World' python code from it using http://test.com/hello.py

How can I install and run webkit2png, say like -
http://test.com/webkit2png.py?url=http://www.google.com&w=800&h=600

Can it use Caching method?
I mean the captured image will get saved into /images/site/ directory

Please help me out
Regards

**Comment by austinpray** [comment]
This is a mac only CLI tool: https://github.com/paulhammond/webkit2png/issues/9

I would recommend using something like phantomjs: http://phantomjs.org/screen-capture.html

Related: https://github.com/paulhammond/webkit2png/pull/76

**Comment by skunkworker** [comment]
How similar is this project? https://github.com/AdamN/python-webkit2png/

It seems to share a similar syntax but requires you to start a xvfb server. I've got it running on ubuntu successfully with a little translation of the command line args.

**Comment by paulhammond** [comment]
I once got webkit2png working behind an Apache webserver running on Mac OS X but it took a lot of fiddling. I don't remember the details, but it involved disabling lots of the built in OS security systems and I really don't recommend it.

Getting something running on linux is also possible, also hard, and involves lots of messing with `xvfb` with something like Chrome Headless mode. But webkit2png is not the tool to do that so I'm going to close this issue. Good luck!
