### ISSUE TITLE
How to set correct --selector parameter

### ISSUE THREAD

**Issue by martinsluka** [paulhammond/webkit2png#84]
Hi Paul, 

I'm not able to write parameter --selector. How it do it, please?

Martin

**Comment by Eunoia** [comment]
You can use a css selector. Take for example, this page. You can use the selector `h1.gh-header-title span.js-issue-title`

The full command to get the title would be:
```
webkit2png -F --selector='h1.gh-header-title span.js-issue-title' https://github.com/paulhammond/webkit2png/issues/84
```
![Uploading githubcompaulhammondwebkit2pngissues84-full.png . . .]()
