### ISSUE TITLE
Cannot render this SVG at any zoom other than 1

### ISSUE THREAD

**Issue by leggers** [paulhammond/webkit2png#85]
First off, a huge THANK YOU for making webkit2png. It's making a project I love possible.

I've been using webkit2png primarily to rasterize SVGs. It is _literally_ the only rasterizer I've found that supports SVG filter effects, 'cause of WebKit. It's been working great at all zoom levels until I tried to render this SVG at any zoom level other than 1: https://www.dropbox.com/s/jxyjb8ajns96jp5/grey.svg?dl=0.

It's odd because WebKit-based browsers render it fine at any zoom level (but beware that opening it in your browser will _really_ slow it down).

Is there anything to be done at the level of this script? Should I file a bug against Python WebKit or WebKit itself?

Thanks again for making webkit2png.

**Comment by paulhammond** [comment]
Hi sorry for the delay in replying. My copy of safari won't render that SVG when I load it directly - it just shows a black screen. Interestingly the resource preview in the web inspector shows it just fine. I think you've found an edge case in webkit itself, I don't know how to debug it further.

Sorry!
