### ISSUE TITLE
What's the difference between  Mac and  Linux version of delay/wait option

### ISSUE THREAD

**Issue by ismail2071** [paulhammond/webkit2png#86]
First ,THANKS for the webkit2png project. 

It helps me a lot.

But i want to ask a question.

In the Mac version,I see the --delay option.

But in the Linux version,i don't see it.

Instead,I see the --wait option.

Is there any difference between --delay AND --wait?

Thanks!!

**Comment by paulhammond** [comment]
Hi! I don't know what linux version you're talking about but the one I made doesn't have a `--wait` option so I can't really describe the differences. Sorry I can't help!
