### ISSUE TITLE
Call webkit2png from python

### ISSUE THREAD

**Issue by tomshinsky** [paulhammond/webkit2png#87]
Hi there,
Is there a nice way to call webkit2png-function from a python avoiding code like this:
os.system( 'webkit2png %s -D %s -T -o %s --selector=.serp-list' % (url, folder, filename))

**Comment by henriquea** [comment]
@tomshinsky you could use https://github.com/adamn/python-webkit2png?

**Comment by paulhammond** [comment]
Hi! I don't think calling this directly from python is going to work - behind the scenes webkit2png uses pyobjc to set up a cocoa NSApplication, and that NSApplication expects to be controlling the program run loop. I don't know of a way to quit the runloop without calling `.terminate()` which will cause the process to exit.

The next version of macOS isn't going to include python so it's likely the next version of webkit2png will be rewritten in a different language.

So no, I don't think this is possible Sorry!
