### ISSUE TITLE
make it work on Linux / Windows

### ISSUE THREAD

**Issue by srid** [paulhammond/webkit2png#9]
Since webkit is available on other platforms as well (via pyqt, pygtkwebkit), it would be nice to make this module portable across those platforms.

**Comment by paulhammond** [comment]
I think it's time to acknowledge that this codebase is never going to support Linux, especially given upcoming Apple deprecation of UIWebView (which can work on Linux) in favor of WKWebView (which can't). I'm going to leave the [pyobjcgtk branch](https://github.com/paulhammond/webkit2png/tree/pywebkitgtk) around as sample code but I'm not going to be working on it any more.

I updated the readme to note that this is a macOS only tool in 4550a8893b8bbdd7dc02accbb5ac6c7f32a09012.
