### ISSUE TITLE
Not working on Ubuntu Linux 14.4

### ISSUE THREAD

**Issue by dadasoz-cuelogic** [paulhammond/webkit2png#95]
Following Modules not available

import Foundation
import WebKit
import AppKit
import Quartz
import objc

**Comment by habibalamin** [comment]
@dadasoz-cuelogic these are all usually found only on OS X machines.

**Comment by insidegui** [comment]
I think this will only run on macOS because it uses AppKit, Quartz and other Apple-only technologies. Maybe the author should add this info to the readme.

**Comment by habibalamin** [comment]
@paulhammond this issue should probably be closed.

**Comment by fake-name** [comment]
Maybe http://www.paulhammond.org/webkit2png/ should, you know, *mention* that it's os-x specific?

**Comment by paulhammond** [comment]
That's a good point. 4550a8893b8bbdd7dc02accbb5ac6c7f32a09012 fixes that. 

There's a [pywebkitgtk branch](https://github.com/paulhammond/webkit2png/tree/pywebkitgtk) where I started trying to get this to work on linux but it's 10 years old and I'll be amazed if it still works. The results weren't great, fonts didn't render well, among other things, but if you want to try to get it to work feel free to use it.
